---
global_exclude_dirs:
    - bootstrap
    - vendor
    - tests

rules:
    composer.dependencies_not_installable:
        enabled: true
    composer.invalid_file:
        enabled: true
    composer.security_issue_in_composer:
        enabled: true
    composer.unfixed_dependency_version:
        enabled: true
    composer.warning:
        enabled: true
    git.user_specific_ignored_file:
        enabled: true
    php.absolute_path_present:
        enabled: true
        allowed_paths: [/dev, /etc, /proc]
    php.bad_mutator_method_name_for_boolean_property:
        enabled: true
    php.class_too_long:
        enabled: true
        max_length: 500
        threshold: 5
    php.commented_out_code:
        enabled: true
    php.contaminant_third_party_component_license:
        enabled: true
    php.debug_statements:
        enabled: true
    php.dynamically_change_configuration:
        enabled: true
    php.file_contains_more_than_one_class:
        enabled: true
    php.for_loop_uses_test_function:
        enabled: true
    php.method_too_long:
        enabled: true
        max_length: 50
        threshold: 5
    php.missing_use_statement:
        enabled: true
    php.neglected_tests:
        enabled: true
    php.object_parameter_not_type_hinted:
        enabled: true
    php.php_magic_methods:
        enabled: true
    php.php_syntax_error:
        enabled: true
    php.too_many_files_per_folder_for_performance:
        enabled: true
        max_count: 10000
    php.unreachable_code:
        enabled: true
    php.unused_local_variable_or_private_member:
        enabled: true
    php.unused_use_statement:
        enabled: true
    php.use_deprecated_function:
        enabled: true
    php.use_exit_function:
        enabled: true
    php.use_global_variable_or_function:
        enabled: true
    php.use_php_ereg_function:
        enabled: true
    php.use_php_eval_function:
        enabled: true
    php.use_php_sleep_function:
        enabled: true
    task_fixme_comment:
        enabled: true
    task_todo_comment:
        enabled: true
    task_xxx_comment:
        enabled: true
    third_party.use_deprecated_class:
        enabled: true
    third_party.use_deprecated_service:
        enabled: true
    web.non_utf8_encoding:
        enabled: true
    xml.syntax_error:
        enabled: true
